language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: "./travis_deploy.sh"
env:
  GHTOKEN:
    secure: ZpM/at6O8TPFwv8vBjd4jUIryG3co/BEgEKxh+Fd2TZ3SiMKyOhPrtwSNBxeDOVbqxcGvp2+vtMZdm/apNvHt6tYrRWmGGLSVe0EfHtACdj4V1A03ye9b/fuE+P+2TwDlQFeF+TEvHpPRPX+t4A8/2bySpfczjG5k3ebhEsEf4o=
